version: '3'

services:
  server:
    image: 'backend'
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/time_series
      - spring.datasource.username=sa
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=create
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=time_series
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
