version: '3'

services:

  frontend:
    image: 'frontend'
    build:
      context: 'frontend/time-series-app'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'

  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=time_series
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  backend:
    image: 'backend'
    build: '.'
    ports:
      - '8080:8080'
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/time_series
      - spring.datasource.username=sa
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=create
    depends_on:
      mysqldb:
        condition: service_healthy
