spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:time_series
    username: sa
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
